config/routes.rb
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do

  root to: "main#index"

  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"

  get "sign-in", to: "sessions#new"
  post "sign-in", to: "sessions#create"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  delete "logout", to: "sessions#destroy"

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  
  resources :tweets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hour.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: self.publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  has_many :tweets, dependent: :destroy
  belongs_to :user

  validates :username, uniqueness: true

  def client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.dig(:twitter, :api_key)
      config.consumer_secret     = Rails.application.credentials.dig(:twitter, :api_secret)
      config.access_token        = token
      config.access_token_secret = secret
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets

  has_secure_password
  
  validates :email, presence: true, format: {with: /\A[^@\s]+@[^@\s]+\z/, message: "Not a valid email address"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "Must be signed in to access this feature" if Current.user.nil?
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    twitter_account.update(
      name: auth.info.name,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret
    )

    redirect_to twitter_accounts_path, notice: "Successfully added your account"
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver_now
    end
    redirect_to root_path, notice: "Email was sent"
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to password_reset_path, alert: "Your token has expired. Please try again."
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
    else
      render :edit, alert: "Something went wrong. Please try again."
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit
  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated successfully"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "Your tweet was scheduled. The world thanks you for sharing your genius!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to tweets_path, notice: "Updated tweet successfully"
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Deleted tweet successfully"
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:show,:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end

  def destroy
    @twitter_account.destroy
    redirect_to twitter_accounts_path, notice: "Successfully removed @#{@twitter_account.username}"
  end

  private

  def set_twitter_account
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schwitter</title>
    <%= favicon_link_tag asset_path('twitterfavicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render partial: "shared/navbar" %>

    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>

    <%= render partial: "shared/footer" %>

  </body>
</html>

app/views/main/index.html.erb
<div>
  <h1>Welcome to Schwitter</h1>
  <h3>Schedule your amazing opinions that the world so desperately needs to hear</h3>
</div>
<%= image_tag("Schwitter.jpg", style: "width:100%; margin-top: 30px; position: relative;") %>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <%= render partial: "shared/form_errors", locals: {form: form} %>
  
  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash.now[:alert] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-primary mt-4" role="alert">
    <%= flash.now[:notice] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="text-center text-muted" style="position: fixed; left: 0; bottom: 0; width: 100%;">
  <p>&copy 2021 Schwitter</p>
</div>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
  <div class="alert alert-danger">
    <% form.object.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-light mb-5 border border-primary">
  <div class="container-fluid">
    <%= link_to "Schwitter", root_path, class: "navbar-brand" %>
      <ul class="navbar-nav">
        <% if Current.user %>
          <li class="nav-item dropdown">
            <%= link_to Current.user.email, "#", class: "nav-link dropdown-toggle", data: {toggle: "dropdown"} %>
            <div class="dropdown-menu">
              <%= link_to "update password", password_path, class: "dropdown-item" %>
              <%= link_to "twitter accounts", twitter_accounts_path, class: "dropdown-item" %>
              <%= link_to "scheduled tweets", tweets_path, class: "dropdown-item" %>
              <%= link_to "logout", logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "login", sign_in_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "sign up", sign_up_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>

  <%= render "shared/form_errors", form: form %>

  <div class="mb-3">
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control"} %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_at %>
    <div class="form-control">
      <%= form.datetime_select :publish_at %>
    </div>
  </div>

  <%= form.button "Schedule", class: "btn btn-primary" %>
  <% if form.object.persisted? %>
  <%= link_to "Delete", form.object, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
  <% end %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="mb-3 card card-body">
  <div class="mb-3">
    <%= image_tag tweet.twitter_account.image, class: "rounded-circle h-50 mr-2" %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank, class: "card-link" %>

    <% if tweet.published? %>
      <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <% else %>
      Scheduled for <%= l tweet.publish_at, format: :long %>
      <%= link_to "Edit tweet", edit_tweet_path(tweet), class: "btn btn-info ml-3" %>
    <% end %>
  </div>
  <%= tweet.body %>
</div>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<div class="d-flex align-items-center justify-content-between mb-4">
  <h1>Scheduled Tweets</h1>
  <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Schedule a tweet", new_tweet_path, class: "btn btn-primary" %>
  <% end %>
</div>

<% if Current.user.twitter_accounts.none? %>
  <%= button_to "Add Account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
<% end %>

<%= render @tweets %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet</h1>

<%= render "form", tweet: @tweet %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between mb-4">
  <h1>Twitter Accounts</h1>
  <%= button_to "Add Account", "/auth/twitter", method: :post, class: "btn btn-primary" %>
</div>

<div class="card mb-4">
  <% @twitter_accounts.each do |twitter_account| %>
    <div class="card-body d-flex align-items-center justify-content-between">
      <div class="me-4">
        <%= image_tag twitter_account.image, class: "rounded-circle h-50 mr-2" %>
        <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank, class: "card-link" %>
      </div>

      <%= button_to "Remove Account", twitter_account, method: :delete, class: "btn btn-secondary", data: {confirm: "Are you sure you want to remove this account?"} %>
    </div>
  <% end %>
</div>